// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8dPakSsyvp0OvYQfxsCuD5t5PcX0CoWc',
    appId: '1:73561006053:ios:531253d6d2bb144216590c',
    messagingSenderId: '73561006053',
    projectId: 'crowdlessbus',
    storageBucket: 'crowdlessbus.firebasestorage.app',
    iosBundleId: 'com.example.croud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8dPakSsyvp0OvYQfxsCuD5t5PcX0CoWc',
    appId: '1:73561006053:ios:531253d6d2bb144216590c',
    messagingSenderId: '73561006053',
    projectId: 'crowdlessbus',
    storageBucket: 'crowdlessbus.firebasestorage.app',
    iosBundleId: 'com.example.croud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLp7thAP6RWqWCz7aQwP6CFH6vqumX0pc',
    appId: '1:73561006053:web:3f0ce7fa848f95cc16590c',
    messagingSenderId: '73561006053',
    projectId: 'crowdlessbus',
    authDomain: 'crowdlessbus.firebaseapp.com',
    storageBucket: 'crowdlessbus.firebasestorage.app',
    measurementId: 'G-BXDVW2G868',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLp7thAP6RWqWCz7aQwP6CFH6vqumX0pc',
    appId: '1:73561006053:web:3f0ce7fa848f95cc16590c',
    messagingSenderId: '73561006053',
    projectId: 'crowdlessbus',
    authDomain: 'crowdlessbus.firebaseapp.com',
    storageBucket: 'crowdlessbus.firebasestorage.app',
    measurementId: 'G-BXDVW2G868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjz9wRN1apFUYmGl_KVMEcM9dbbB-HpMw',
    appId: '1:73561006053:android:cff9be48b5fedc1816590c',
    messagingSenderId: '73561006053',
    projectId: 'crowdlessbus',
    storageBucket: 'crowdlessbus.firebasestorage.app',
  );
}
